server:
  port: 9090

spring:
  application:
    name: product-service
  jpa:
    hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root123

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

product:
  name:
    url: https://redsky.target.com/v2/pdp/tcin/{id}?excludes=taxonomy,price,promotion,bulk_ship,rating_and_review_reviews,rating_and_review_statistics,question_answer_statistics
    cache:
      spec: maximumSize=10000,expireAfterWrite=10m
  price:
    url: http://localhost:9090/api/product/{productId}/price             

---
spring:
  profiles: test
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect   